### ISSUE TITLE
Android "Duplicate analytics client created with tag"

### ISSUE THREAD

**Issue by threesquared** [leoilab/react-native-analytics-segment-io#3]
When I am running my app in an android simulator and reload the RN javascript I get this error. It seems like the setup method on the `SegmentModule.java` is being called twice which in turn calls `Analytics.setSingletonInstance()` which can only be called once.

**Comment by kasperkronborg** [comment]
@kevinpelgrims

**Comment by casperstorm** [comment]
Hi @threesquared – I've just merged PR #4 which @kevinpelgrims made, which should fix this issue. I will close this issue now, but feel free to reopen if you face any problems.

Thanks for reporting it @threesquared, and thanks for the PR @kevinpelgrims.

**Comment by threesquared** [comment]
I am still getting this error with the latest `1.2.1` version. I am calling `Analytics.setup()`
 in my main `app.js` and I have also tried in the `index.android.js` but having the same issue. Also this issue seems to also happen in the built app and not just the simulator when you open the app again from being in the background. I have attached a crashalytics exception.

My Java is not so great but I will have a look and see if there is anything I can do about it.

![screen shot 2017-09-19 at 11 52 54](https://user-images.githubusercontent.com/892142/30589181-547367fa-9d31-11e7-83a6-125bbc9f2557.png)

**Comment by kasperkronborg** [comment]
@kevinpelgrims Any ideas?

**Comment by kevinpelgrims** [comment]
I had no issues with refreshing when I tested after the latest changes, but I will take a look.

**Comment by kevinpelgrims** [comment]
You can only create the analytics object once, and on Android, unlike on iOS, you cannot update the properties once they are set.
So I will make sure that `setup()` returns a promise that either resolves if analytics is set up properly, or rejects if the analytics object is already created.
That way consumer of the lib don't get strange errors, but people who try to call `setup()` multiple times at least get notified that they are doing something wrong.
I will also update the documentation.

**Comment by threesquared** [comment]
@kevinpelgrims thank you. Moving the `setup()` method into my index file stopped crashing on backgrounding the app but still having the issue when reloading the JS in the simulator. I think the above solution will fix that.

**Comment by carlbenson** [comment]
In my case, I have a hybrid app and would like to reuse the `Analytics` instance already created. How would one go about achieving this?

**Comment by casperstorm** [comment]
@carlbenson We don't see this being supported, please educate us if we are wrong.
@threesquared I have merged and bumped the module. Version 2.0.1 has the changes you need. Thank you for reporting the issue.

**Comment by shyaniv7** [comment]
We have the exact same issue, would be nice to check if analytics is already initialized or ignore any initialization after the initial
